baseURL = 'https://nhatthanh020996.github.io'
languageCode = 'en-us'
theme = 'hugo-theme-cleanwhite'
title = 'breadcrumbscollector'

disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "/img/posts/isolation/title_image.jpeg"
  SEOTitle = "breadcrumbscollector"
  description = "赵化冰，程序员, 开源爱好者，生活探险家 | 这里是 赵化冰 的博客，与你一起发现更大的世界。"
  keyword = "networing, operating system, computer architecture, python, socket programing, database"

  image_404 = "img/background.jpeg"
  title_404 = "Page Not Found :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Backend Developer"
  sidebar_avatar = "img/avatar.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  #reward = true 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  #friends = true
  bookmarks = true
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  #rss            = true 
  email          = "nhatthanh020996@gmail.com"
  github         = "https://github.com/nhatthanh020996"
  linkedin       = "https://www.linkedin.com/in/tran-nhat-thanh-9219bb184/"
  

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  #[[params.addtional_menus]]
  #title =  "ARCHIVE"
  #href =  "/archive/"
  #[[params.addtional_menus]]
  #title =  "NOTES"
  #href =  "/notes/"
  #[[params.addtional_menus]]
  #title =  "ABOUT"
  #href =  "/about/index/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.giscus]
data_repo="nhatthanh020996/giscus-blog-comments"
data_repo_id="nhatthanh020996/giscus-blog-comments"
data_category="Announcements"
data_category_id="your category id"
data_mapping="pathname"
data_reactions_enabled="0"
data_theme="light"
data_lang="en"
crossorigin="anonymous"

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 


[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
